# Generated by Django 4.0.4 on 2022-05-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='priority',
        ),
    ]
