# Generated by Django 4.0.4 on 2022-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='deletion_comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
